### ISSUE TITLE
Drivers Can't work at Win 11 23H2

### ISSUE THREAD

**Issue by sinfee** [lc700x/MagicTrackPad2_Windows_Precision_Drivers#1]
In Win11 23H2 , After the driver is installed and connected to the trackpad, it will automatically disconnect after the connection is successful, and the device is deleted

**Comment by lc700x** [comment]
Is it Windows 11 Pro?
Are you using the wired connection or bluetooth?

**Comment by tomasmark79** [comment]
I don't recommend Imbushuo's driver because its lagged on my Win11. The original from Apple works better.

**Comment by sneakyjoeru** [comment]
> Dism /online /Get-Drivers /Format:Table | findstr "apple"

That's a slightly better line to get drivers only with apple name in them.
